STAT_ABBREVS = {
    "atk": "Attack",
    "def": "Defense",
    "hp": "HP",
    "atk_p": "Attack %",
    "def_p": "Defense %",
    "hp_p": "HP %",
    "cr": "Crit Rate",
    "cd": "Crit Damage",
    "er": "Energy Recharge",
    "em": "Elemental Mastery",
    "hb": "Healing Bonus",
    "pyro": "Pyro DMG Bonus",
    "hydro": "Hydro DMG Bonus",
    "anemo": "Anemo DMG Bonus",
    "electro": "Electro DMG Bonus",
    "dendro": "Dendro DMG Bonus",
    "cryo": "Cryo DMG Bonus",
    "geo": "Geo DMG Bonus",
    "spd": "Speed",
    "ehr": "Effect Hit Rate",
    "eff_res": "Effect Resistance",
    "be": "Break Effect",
    "physical": "Physical DMG Bonus",
    "fire": "Fire DMG Bonus",
    "ice": "Ice DMG Bonus",
    "lightning": "Lightning DMG Bonus",
    "wind": "Wind DMG Bonus",
    "quantum": "Quantum DMG Bonus",
    "imaginary": "Imaginary DMG Bonus",
    "pen": "Penetration",
    "pen_r": "Penetration Ratio",
    "ap": "Anomaly Proficiency",
    "am": "Anomaly Mastery",
    "ether": "Ether DMG Bonus"
}
